require: rubocop-rake

AllCops:
  AllowSymlinksInCacheRootDirectory: true
  TargetRubyVersion: 3.2
  Exclude:
    - "**/bin/**/*"
    - "**/node_modules/**/*"
    - "**/.git/**/*"
  AutoCorrect: true
  NewCops: enable
  StyleGuideBaseURL: https://rubystyle.guide
#Rails:
#  StyleGuideBaseURL: https://rails.rubystyle.guide

# TODO: enable Gemspec/DevelopmentDependencies and pick an `EnforcedStyle`
Gemspec/DevelopmentDependencies:
  Enabled: false

Layout/AccessModifierIndentation:
  EnforcedStyle: outdent
Layout/EmptyLinesAroundAccessModifier:
  EnforcedStyle: only_before
Layout/EmptyLinesAroundAttributeAccessor:
  Enabled: false
Layout/EndAlignment:
  EnforcedStyleAlignWith: start_of_line
#Layout/ExtraSpacing:
#  Enabled: false  # Disabled pending resoulution of #5657
Layout/FirstHashElementIndentation:
  EnforcedStyle: consistent
Layout/HashAlignment:
  EnforcedColonStyle: table
  EnforcedHashRocketStyle: table
Layout/LineLength:
  Enabled: false
#Layout/SpaceAroundOperators:
#  Enabled: false # Disabled pending resoulution of #5657
Layout/SpaceInsideArrayLiteralBrackets:
  EnforcedStyle: space

Lint/AmbiguousOperator:
  Enabled: false

Metrics/AbcSize:
  Enabled: false
Metrics/BlockLength:
  IgnoredMethods:
    - aasm
    - included
    - class_methods
    - namespace
    - task
Metrics/MethodLength:
  Max: 25
Metrics/ParameterLists:
  Enabled: false

Naming/MethodParameterName:
  AllowedNames:
    - as
    - to
    - io
    - id

Style/AccessorGrouping:
  Enabled: false
Style/Alias:
  EnforcedStyle: prefer_alias_method
Style/ClassAndModuleChildren:
  Enabled: false
Style/CommentedKeyword:
  Enabled: false
Style/Documentation:
  Enabled: false
Style/DoubleNegation:
  Enabled: false
Style/EmptyMethod:
  EnforcedStyle: expanded
Style/FrozenStringLiteralComment:
  EnforcedStyle: always_true
  SafeAutoCorrect: true
Style/HashSyntax:
  EnforcedStyle: ruby19
Style/Lambda:
  EnforcedStyle: literal
Style/MultilineBlockChain:
  Enabled: false
Style/MultilineIfModifier:
  Enabled: false
Style/SpecialGlobalVars:
  EnforcedStyle: use_perl_names
Style/SymbolArray:
  MinSize: 1
Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma