set(_Ruby_DEBUG_OUTPUT ${VERBOSE_MODE})
set(RUBY_FIND_VERSION 3.2)
find_package(Ruby 3.2 REQUIRED Ruby_FIND_VIRTUALENV)
target_link_libraries("${EXTENSION_NAME}" PUBLIC ${Ruby_LIBRARIES})
target_include_directories("${EXTENSION_NAME}" PUBLIC ${Ruby_INCLUDE_DIRS})
target_include_directories("${EXTENSION_NAME}" PRIVATE ${RICE_INCLUDE_PATH})
if (DEV_MODE)
    set_target_properties("${EXTENSION_NAME}" PROPERTIES INSTALL_RPATH_USE_LINK_PATH ON)
endif()
# FIXME: ruby wants to add it's own flags (e.g. enabling stack protection; they're in RbConfig)
message(STATUS "libruby ${Ruby_VERSION} found at ${Ruby_LIBRARY}")
message(STATUS "Rice ${RICE_VERSION} found in ${RICE_INCLUDE_PATH}")
