#ifndef EXTCONF_H
#define EXTCONF_H
#define HAVE_BOOST_EXCEPTION_ALL_HPP 1
#define HAVE_BACKTRACE_H 1
#define BOOST_STACKTRACE_USE_BACKTRACE 1
#define BOOST_ENABLE_ASSERT_DEBUG_HANDLER 1
#define BOOST_STACKTRACE_LINK 1
#define BOOST_STACKTRACE_SUPPORT 1
#define HAVE_VALGRIND_VALGRIND_H 1
#define SIMPLERBBLE_DEBUG 1
#endif
